#include "stm32f4xx_hal.h"  // 必须引入具体的芯片 HAL 库
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include <stdio.h>
#include <string.h>

// ==========================================================
// 1. 全局硬件句柄与 RTOS 资源声明
// ==========================================================
UART_HandleTypeDef huart1; // 用于激光雷达/ROS2通信
I2C_HandleTypeDef hi2c1;   // 用于读取陀螺仪(IMU)
CAN_HandleTypeDef hcan1;   // 用于 CANOpen 节点通信

TaskHandle_t TaskHandle_Motor;
TaskHandle_t TaskHandle_Lidar;
TaskHandle_t TaskHandle_CAN;
SemaphoreHandle_t xI2C_Mutex; // I2C 总线互斥锁

// ==========================================================
// 2. 底层硬件初始化函数声明
// ==========================================================
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_I2C1_Init(void);
static void MX_CAN1_Init(void);

// ==========================================================
// 3. 任务实体函数声明
// ==========================================================
void Task_MotorControl(void *pvParameters);
void Task_LidarParse(void *pvParameters);
void Task_CANOpen(void *pvParameters);
void Task_StackMonitor(void *pvParameters);

// ==========================================================
// 主函数 (Entry Point)
// ==========================================================
int main(void) {
    // 1. 复位所有外设，初始化 Flash 接口和 Systick
    HAL_Init();

    // 2. 配置系统时钟 (配置 RCC_CFGR 等，建立系统心跳)
    SystemClock_Config();

    // 3. 初始化所有底层硬件
    MX_GPIO_Init();
    MX_USART1_UART_Init();
    MX_I2C1_Init();
    MX_CAN1_Init();

    // 4. 创建 RTOS 资源
    xI2C_Mutex = xSemaphoreCreateMutex();
    if (xI2C_Mutex == NULL) {
        // 内存不足，创建失败，死机保护
        while(1); 
    }
    // 使用由 FreeRTOS 提供的互斥量 (mutex) 而不是二值信号量，
    // 以启用优先级继承 (Priority Inheritance)，缓解优先级翻转问题。

    // 5. 创建系统任务 (注意分配实际的堆栈大小，单位是 Word)
    xTaskCreate(Task_MotorControl, "Motor", 256, NULL, 5, &TaskHandle_Motor);
    xTaskCreate(Task_LidarParse,  "Lidar", 512, NULL, 3, &TaskHandle_Lidar);
    xTaskCreate(Task_CANOpen,     "CAN",   256, NULL, 1, &TaskHandle_CAN);
    // 任务用于监控每个任务的栈高水位（Stack High Water Mark）
    xTaskCreate(Task_StackMonitor, "StackMon", 256, NULL, 2, NULL);

    // 6. 启动调度器，接管 CPU
    vTaskStartScheduler();

    // 永远不应该执行到这里，除非 FreeRTOS 堆内存耗尽
    while (1) {
    }
}

// ==========================================================
// 4. 任务实体具体实现
// ==========================================================

// [最高优先级] 电机与运动学解算任务
void Task_MotorControl(void *pvParameters) {
    uint8_t imu_data[6];
    
    for(;;) {
        // 尝试获取 I2C 总线锁，等待 10 个 RTOS Tick
        if (xSemaphoreTake(xI2C_Mutex, pdMS_TO_TICKS(10)) == pdTRUE) {
            
            // 成功获取锁，调用 HAL 库读取 MPU6050/BMI088
            HAL_I2C_Mem_Read(&hi2c1, 0xD0, 0x3B, I2C_MEMADD_SIZE_8BIT, imu_data, 6, HAL_MAX_DELAY);
            
            // 释放锁，允许其他任务使用 I2C
            xSemaphoreGive(xI2C_Mutex);
            
            // TODO: 执行 FOC 算法或 PID 计算，并通过 PWM 输出
            
        } else {
            // 锁获取失败，触发总线复位或安全停机逻辑
        }
        
        // 绝对延时，保证控制环路严格的 2ms (500Hz) 运行频率
        vTaskDelay(pdMS_TO_TICKS(2)); 
    }
}

// [中等优先级] 激光雷达 / ROS2 串口协议解析任务
void Task_LidarParse(void *pvParameters) {
    uint8_t rx_buffer[128];
    
    for(;;) {
        // 工业级做法：不在这里死等串口数据，而是使用 FreeRTOS 队列或任务通知
        // 假设 UART 接收中断（或 DMA）完成一帧接收后，发送了任务通知唤醒此任务
        if(ulTaskNotifyTake(pdTRUE, portMAX_DELAY) > 0) {
            
            // 此时再去处理缓存中的数据
            // TODO: 校验帧头帧尾、CRC 校验、提取速度向量
            
        }
    }
}

// [低优先级] CAN 总线心跳与状态机管理
void Task_CANOpen(void *pvParameters) {
    for(;;) {
        // 检查电池电压、温度传感器等非高实时性数据
        // 发送 CANOpen NMT 心跳包
        
        // 低优先级任务休眠 100ms
        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

// ==========================================================
// 5. 堆栈溢出保护钩子函数 (需在 FreeRTOSConfig.h 开启)
// ==========================================================
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName) {
    // 禁用所有中断，切断电机 PWM 输出
    __disable_irq(); 
    
    // 可以在这里通过串口发送紧急错误日志
    // printf("Stack Overflow in: %s\r\n", pcTaskName);
    
    // 强制复位系统
    NVIC_SystemReset(); 
}

// ==========================================================
// 6. 底层硬件初始化桩函数 (通常由芯片厂商代码生成工具自动生成)
// ==========================================================
void SystemClock_Config(void) {
    // 实际项目中，这里会配置 RCC_CR, RCC_PLLCFGR, RCC_CFGR 等寄存器
    // 将 HPRE, PPRE1, PPRE2 配置为你之前提到的最佳分频
}
static void MX_GPIO_Init(void) {
    // Minimal placeholder GPIO init for development/testing.
    // Production code should be generated by CubeMX or hand-written per board.
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
}

// 简单的栈监控任务：周期性打印每个任务的高水位（单位：栈字）
void Task_StackMonitor(void *pvParameters) {
    char buf[128];
    for (;;) {
        UBaseType_t motor = uxTaskGetStackHighWaterMark(TaskHandle_Motor);
        UBaseType_t lidar = uxTaskGetStackHighWaterMark(TaskHandle_Lidar);
        UBaseType_t can = uxTaskGetStackHighWaterMark(TaskHandle_CAN);
        UBaseType_t self = uxTaskGetStackHighWaterMark(NULL);
        int len = snprintf(buf, sizeof(buf), "StackHighWater (words): Motor=%lu Lidar=%lu CAN=%lu Self=%lu\r\n",
                           (unsigned long)motor, (unsigned long)lidar, (unsigned long)can, (unsigned long)self);
        HAL_UART_Transmit(&huart1, (uint8_t*)buf, (uint16_t)len, HAL_MAX_DELAY);
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}